require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServingsController do

  # This should return the minimal set of attributes required to create a valid
  # Serving. As you add validations to Serving, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all servings as @servings" do
      serving = Serving.create! valid_attributes
      get :index, {}, valid_session
      assigns(:servings).should eq([serving])
    end
  end

  describe "GET show" do
    it "assigns the requested serving as @serving" do
      serving = Serving.create! valid_attributes
      get :show, {:id => serving.to_param}, valid_session
      assigns(:serving).should eq(serving)
    end
  end

  describe "GET new" do
    it "assigns a new serving as @serving" do
      get :new, {}, valid_session
      assigns(:serving).should be_a_new(Serving)
    end
  end

  describe "GET edit" do
    it "assigns the requested serving as @serving" do
      serving = Serving.create! valid_attributes
      get :edit, {:id => serving.to_param}, valid_session
      assigns(:serving).should eq(serving)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Serving" do
        expect {
          post :create, {:serving => valid_attributes}, valid_session
        }.to change(Serving, :count).by(1)
      end

      it "assigns a newly created serving as @serving" do
        post :create, {:serving => valid_attributes}, valid_session
        assigns(:serving).should be_a(Serving)
        assigns(:serving).should be_persisted
      end

      it "redirects to the created serving" do
        post :create, {:serving => valid_attributes}, valid_session
        response.should redirect_to(Serving.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serving as @serving" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serving.any_instance.stub(:save).and_return(false)
        post :create, {:serving => { "user" => "invalid value" }}, valid_session
        assigns(:serving).should be_a_new(Serving)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serving.any_instance.stub(:save).and_return(false)
        post :create, {:serving => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serving" do
        serving = Serving.create! valid_attributes
        # Assuming there are no other servings in the database, this
        # specifies that the Serving created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Serving.any_instance.should_receive(:update).with({ "user" => "MyString" })
        put :update, {:id => serving.to_param, :serving => { "user" => "MyString" }}, valid_session
      end

      it "assigns the requested serving as @serving" do
        serving = Serving.create! valid_attributes
        put :update, {:id => serving.to_param, :serving => valid_attributes}, valid_session
        assigns(:serving).should eq(serving)
      end

      it "redirects to the serving" do
        serving = Serving.create! valid_attributes
        put :update, {:id => serving.to_param, :serving => valid_attributes}, valid_session
        response.should redirect_to(serving)
      end
    end

    describe "with invalid params" do
      it "assigns the serving as @serving" do
        serving = Serving.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serving.any_instance.stub(:save).and_return(false)
        put :update, {:id => serving.to_param, :serving => { "user" => "invalid value" }}, valid_session
        assigns(:serving).should eq(serving)
      end

      it "re-renders the 'edit' template" do
        serving = Serving.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serving.any_instance.stub(:save).and_return(false)
        put :update, {:id => serving.to_param, :serving => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serving" do
      serving = Serving.create! valid_attributes
      expect {
        delete :destroy, {:id => serving.to_param}, valid_session
      }.to change(Serving, :count).by(-1)
    end

    it "redirects to the servings list" do
      serving = Serving.create! valid_attributes
      delete :destroy, {:id => serving.to_param}, valid_session
      response.should redirect_to(servings_url)
    end
  end

end
